// 對手角色：長相（扁平插畫參數）、打法、台詞。

import type { AiStyle } from './ai'

export type Hair = 'perm' | 'short' | 'spiky' | 'bald' | 'bun' | 'long' | 'bob' | 'slick' | 'ponytail'
export type Extra =
  | 'glasses'
  | 'sunglasses'
  | 'cap'
  | 'earrings'
  | 'mustache'
  | 'beard'
  | 'bow'
  | 'tie'
  | 'headphones'
  // 你自己的造型才有的
  | 'helmet'
  | 'douli'
  | 'headband'
  | 'crown'
  | 'hairflower'

export interface Look {
  skin: string
  hair: Hair
  hairColor: string
  shirt: string
  bg: string
  extras?: Extra[]
  capColor?: string
}

export type LineKey =
  | 'hello'
  | 'pon'
  | 'chi'
  | 'kong'
  | 'ting'
  | 'tsumo'
  | 'ron'
  | 'dealIn'
  | 'otherWin'
  | 'exhausted'
  | 'matchWin'
  | 'matchLose'
  /** 用絕招時 */
  | 'skill'
  /** 你嗆他時回嘴 */
  | 'reply'
  /** 好感度 Lv3 以上的開場招呼 */
  | 'friend'
  /** 宿敵：你又放槍給他、或開場看到你 */
  | 'rival'
  /** 你報仇成功（宿敵付錢給你） */
  | 'revenged'
  /** 你想太久：催你 */
  | 'slow'
  /** 有人放槍：在旁邊幸災樂禍 */
  | 'laugh'

export interface Character {
  id: string
  name: string
  bio: string
  look: Look
  style: AiStyle
  lines: Partial<Record<LineKey, string[]>>
  /** 對手也會用的絕招（每場次數） */
  skill?: { id: 'swap' | 'peek' | 'lucky'; uses: number }
  /** 出牌節奏：1 是一般，大於 1 想比較久 */
  tempo?: number
}

const SKIN = '#f6c9a8'
const SKIN2 = '#e8b48f'

export const CHARACTERS: Record<string, Character> = {
  meiling: {
    id: 'meiling',
    tempo: 0.9,
    name: '大舅媽',
    bio: '巷口美髮院老闆娘。八卦第一名，能碰就碰。',
    look: { skin: SKIN, hair: 'perm', hairColor: '#3b2a3f', shirt: '#ff6f91', bg: '#ffe3ea', extras: ['earrings'] },
    style: { speed: 0.8, defense: 0.2, greed: 0.2, mistakes: 0.5 },
    lines: {
      hello: ['來來來，今天手氣一定很好！', '打完這圈我還要回去幫客人染頭髮喔'],
      pon: ['碰！這張我等很久了', '碰～謝啦！'],
      chi: ['吃一下吃一下', '這張我要了喔'],
      kong: ['槓！開花開花～'],
      ting: ['欸，我好像快了喔～', '嘿嘿，你們小心點'],
      tsumo: ['自摸！大家掏錢掏錢～', '哎唷，自己摸到了啦'],
      ron: ['胡啦！謝謝你喔～', '就是這張！'],
      dealIn: ['唉唷，打錯了啦', '早知道就不打這張'],
      otherWin: ['好啦好啦，給你胡', '下一把換我'],
      exhausted: ['流局！再來再來'],
      matchWin: ['今天手氣真的不錯耶～'],
      matchLose: ['下次再找你們報仇！'],
      reply: ['欸～你很囂張喔', '好啦好啦，舅媽讓你', '你再嗆，下次剪頭髮算你貴一點', '嘴巴這麼壞，小心沒人要喔～'],
      friend: ['欸你又來了！舅媽最喜歡跟你打', '今天幫你留了最好的位子喔'],
      rival: ['又是你喔？舅媽今天又要收你錢了～', '你是不是專門來送舅媽紅包的？'],
      revenged: ['唉唷，被你討回去了啦'],
      slow: ['欸～你在想什麼啦，頭髮都要白了', '快點快點，我客人還在等我染頭髮'],
      laugh: ['哎唷～放槍囉，舅媽都看到了', '哈哈，這個我要去巷口講'],
    },
  },
  lin: {
    id: 'lin',
    tempo: 1.25,
    name: '鄒家雀神',
    bio: '鄒家公認的麻將高手，退休公務員。打牌跟做人一樣穩，很少放槍。',
    look: { skin: SKIN, hair: 'short', hairColor: '#9aa0a6', shirt: '#f0c64a', bg: '#e4f6ef', extras: ['cap', 'mustache'], capColor: '#13a37f' },
    style: { speed: 0.3, defense: 0.8, greed: 0.1, mistakes: 0.3 },
    lines: {
      hello: ['慢慢打，不要急', '年輕人，讓我教你兩招'],
      pon: ['碰。'],
      chi: ['吃。'],
      kong: ['槓。'],
      ting: ['嗯……差不多了'],
      tsumo: ['自摸，不好意思啦'],
      ron: ['胡了，承讓承讓'],
      dealIn: ['老了老了，眼睛不好'],
      otherWin: ['打得不錯'],
      exhausted: ['流局也好，安全'],
      matchWin: ['薑還是老的辣'],
      matchLose: ['後生可畏喔'],
      reply: ['年輕人，沉住氣', '呵呵，好好好', '年輕人，火氣大傷身', '嗆贏了，牌也不會變好'],
      friend: ['你來啦，茶剛泡好', '跟你打牌，我很放心'],
      rival: ['年輕人，又是你啊', '上次那幾張，還記得吧？'],
      revenged: ['好，這下扯平了'],
      slow: ['慢慢想沒關係，我退休了很有空', '想太久，好牌也會跑掉喔'],
      laugh: ['呵呵，年輕人要多繳點學費', '這張，我早就知道會出事'],
    },
  },
  kai: {
    id: 'kai',
    tempo: 1.1,
    name: '小姨丈',
    bio: '工程師。說自己用機率打牌，其實超好勝。',
    look: { skin: SKIN, hair: 'short', hairColor: '#1d2a4a', shirt: '#3a6df0', bg: '#e6edff', extras: ['glasses'] },
    style: { speed: 0.5, defense: 0.5, greed: 0.3, mistakes: 0.35 },
    lines: {
      hello: ['我算過了，這桌我期望值最高'],
      pon: ['碰，進張數 +8'],
      chi: ['吃，效率最佳解'],
      kong: ['槓，變異數拉高'],
      ting: ['聽了。機率大概 38%'],
      tsumo: ['自摸，符合預期'],
      ron: ['胡了，你那張很危險欸'],
      dealIn: ['……這不科學'],
      otherWin: ['樣本數太小啦'],
      matchWin: ['數據不會說謊'],
      matchLose: ['回去調一下參數'],
      reply: ['嘴砲不影響機率', '我記下來了', '你的嘴砲沒有統計顯著性', '已記錄，下一把報復'],
      friend: ['根據紀錄，跟你打我最開心', '你的打法我建模了，還是看不懂'],
      rival: ['你放槍給我的機率，高得不正常', '根據紀錄，你是我的提款機'],
      revenged: ['……好，這筆我重新計算'],
      slow: ['你的思考時間已經超過標準差了', '要不要我幫你跑個模擬？'],
      laugh: ['這個放槍機率，我算過了，很高', '哈，完全符合模型預測'],
    },
  },
  wang: {
    id: 'wang',
    tempo: 1.1,
    name: '王經理',
    bio: '部門主管。只做大牌，放槍也要有面子。',
    look: { skin: SKIN2, hair: 'slick', hairColor: '#2b2b2b', shirt: '#2f4b7c', bg: '#e8ecf5', extras: ['tie', 'glasses'] },
    style: { speed: 0.3, defense: 0.35, greed: 0.8, mistakes: 0.3 },
    lines: {
      hello: ['今天不談公事，大家輕鬆打'],
      pon: ['碰，這就是決策力'],
      chi: ['吃，靈活調度'],
      kong: ['槓，擴大營收'],
      ting: ['這手不小喔'],
      tsumo: ['自摸！年終有著落了'],
      ron: ['胡了，KPI 達成'],
      dealIn: ['……這張算我請客'],
      otherWin: ['不錯，明年加薪考慮一下'],
      matchWin: ['領導就是要以身作則'],
      matchLose: ['今天先讓你們贏'],
      reply: ['年輕人很有衝勁嘛', '這個態度我喜歡', '這種態度，年終要扣分喔', '年輕人，說話要看場合'],
      friend: ['你來了，今天我請客', '年終考績，你是 A'],
      rival: ['又是你，年終靠你了', '你是我今年最好的客戶'],
      revenged: ['好，這次算你贏回去'],
      slow: ['開會都沒你這麼久', '時間就是金錢，你在燒我的錢'],
      laugh: ['這個決策，下次開會要檢討', '哈哈，這筆列入考績'],
    },
  },
  xiaomei: {
    id: 'xiaomei',
    tempo: 1.3,
    name: '小美',
    bio: '新進會計。第一次打尾牙麻將，新手運超強。',
    look: { skin: SKIN, hair: 'bob', hairColor: '#7a4a2a', shirt: '#ffb3c7', bg: '#fff0f4', extras: ['bow'] },
    style: { speed: 0.6, defense: 0.2, greed: 0.2, mistakes: 0.6 },
    lines: {
      hello: ['我不太會打，請大家多指教～'],
      pon: ['這個可以碰嗎？碰！'],
      chi: ['我吃～是這樣吃嗎？'],
      kong: ['四張一樣的可以槓對吧？'],
      ting: ['咦，這樣是聽牌嗎？'],
      tsumo: ['我……我好像自摸了？'],
      ron: ['胡了！新手運新手運'],
      dealIn: ['啊，對不起！'],
      otherWin: ['好厲害喔'],
      matchWin: ['謝謝大家讓我～'],
      matchLose: ['下次我會更努力的！'],
      reply: ['嗚嗚，不要兇我啦', '好啦，我快一點', '嗚嗚你好兇，我要跟經理講', '我、我才不怕你咧！'],
      friend: ['你又來了～今天也請多指教！', '跟你打牌我比較不緊張耶'],
      rival: ['又是你！謝謝你一直幫我～', '你是不是故意讓我的？'],
      revenged: ['嗚嗚，被你討回去了'],
      slow: ['那個……輪到你了喔？', '要不要我幫你算一下？'],
      laugh: ['啊，好可憐喔……可是好好笑', '對不起，我不是故意笑的～'],
    },
  },
  jie: {
    id: 'jie',
    tempo: 0.75,
    name: '阿傑',
    bio: '業務一哥。節奏超快，能吃就吃。',
    look: { skin: SKIN2, hair: 'spiky', hairColor: '#3a2618', shirt: '#ff8a3d', bg: '#fff1e3' },
    style: { speed: 0.95, defense: 0.3, greed: 0.2, mistakes: 0.3 },
    lines: {
      hello: ['快點快點，打完還要去續攤'],
      pon: ['碰碰碰！'],
      chi: ['吃！節奏要快'],
      kong: ['槓！衝業績'],
      ting: ['聽了聽了，誰要放槍'],
      tsumo: ['自摸！業績達標'],
      ron: ['胡！謝謝老闆'],
      dealIn: ['哎呀，衝太快了'],
      otherWin: ['下一把我一定贏'],
      matchWin: ['今晚續攤我請！'],
      matchLose: ['輸了？不可能！再一場！'],
      reply: ['你才慢咧！', '來啊，誰怕誰', '嗆我？我業績比你好', '來啊，看誰先胡！'],
      friend: ['兄弟！打完一起去續攤', '你來我就開心，快坐快坐'],
      rival: ['老客戶又來了！', '你每次都送我，太夠意思了吧'],
      revenged: ['哇，被你反殺！'],
      slow: ['兄弟，客戶都跑掉了啦', '你是在等天亮喔？'],
      laugh: ['哈哈哈，送分送分！', '這單我幫你記下來了'],
    },
  },
  ama: {
    id: 'ama',
    tempo: 1.35,
    name: '阿嬤',
    bio: '打了五十年麻將。防守滴水不漏。',
    look: { skin: SKIN, hair: 'bun', hairColor: '#c9ccd1', shirt: '#8b5cf6', bg: '#f1ebff', extras: ['glasses', 'earrings'] },
    style: { speed: 0.4, defense: 0.95, greed: 0.4, mistakes: 0.05 },
    skill: { id: 'peek', uses: 1 },
    lines: {
      hello: ['乖孫，阿嬤不會讓你喔', '來，陪阿嬤打一圈'],
      pon: ['碰啦'],
      chi: ['阿嬤吃一下'],
      kong: ['槓，阿嬤手氣好'],
      ting: ['阿嬤要胡囉'],
      tsumo: ['自摸！紅包拿來'],
      ron: ['胡！阿嬤眼睛還很利'],
      dealIn: ['哎唷，阿嬤老花了'],
      otherWin: ['不錯喔，有阿嬤的遺傳'],
      exhausted: ['流局，再來'],
      matchWin: ['紅包阿嬤先收著～'],
      matchLose: ['乖孫長大了喔'],
      reply: ['乖孫，對阿嬤講話要客氣', '哎唷，嘴巴這麼甜', '阿嬤打麻將的時候，你還沒出生喔', '再嗆，今年紅包減半'],
      friend: ['乖孫來了！阿嬤煮了湯圓', '跟阿嬤打，輸了也有紅包拿'],
      skill: ['阿嬤看一下你的牌喔～'],
      rival: ['乖孫，又來送阿嬤零用錢喔？', '你每次都打給阿嬤，阿嬤記得喔'],
      revenged: ['哎唷，乖孫討回去了'],
      slow: ['乖孫，阿嬤等到都想睡了', '想那麼久，阿嬤都可以煮一鍋飯了'],
      laugh: ['哎唷，阿嬤教過你不要打那張', '呵呵，繳學費囉'],
    },
  },
  erjiu: {
    id: 'erjiu',
    tempo: 0.85,
    name: '二舅',
    bio: '家族嘴砲王。喝了兩杯之後更衝。',
    look: { skin: '#f0a987', hair: 'bald', hairColor: '#3a2618', shirt: '#ffb020', bg: '#fff5d6', extras: ['beard'] },
    style: { speed: 0.85, defense: 0.15, greed: 0.5, mistakes: 0.4 },
    lines: {
      hello: ['今年二舅要把紅包贏回來！'],
      pon: ['碰！看到沒！'],
      chi: ['吃！'],
      kong: ['槓！運氣來了擋不住'],
      ting: ['二舅聽牌了，誰敢放槍'],
      tsumo: ['自摸！乾杯乾杯'],
      ron: ['胡啦！就知道你會打這張'],
      dealIn: ['欸，這張怎麼會有人要'],
      otherWin: ['好啦，算你厲害'],
      matchWin: ['今年發財啦！'],
      matchLose: ['明年……明年一定'],
      reply: ['小朋友，二舅教你做人', '哈哈，有種！', '哈哈，二舅嗆人的時候你還在包尿布！', '有種！等一下乾一杯'],
      friend: ['來來來，二舅今天跟你同一國！', '你來了，二舅的紅包有救了'],
      rival: ['哈哈，又是你！二舅的招財貓！', '你是不是二舅失散多年的提款機？'],
      revenged: ['好小子，有你的！'],
      slow: ['欸，你是睡著了喔？', '快點啦，我的酒都退冰了'],
      laugh: ['哈哈哈！這張也敢打喔！', '來來來，大家拍手！'],
    },
  },
  biaomei: {
    id: 'biaomei',
    tempo: 1.2,
    name: '表妹',
    bio: '大學生。一邊滑手機一邊打，偶爾很準。',
    look: { skin: SKIN, hair: 'long', hairColor: '#2a1c14', shirt: '#33c2a0', bg: '#e0f7f1', extras: ['headphones'] },
    style: { speed: 0.5, defense: 0.3, greed: 0.3, mistakes: 0.5 },
    lines: {
      hello: ['等一下我回個訊息……好了好了'],
      pon: ['喔，碰'],
      chi: ['吃～'],
      kong: ['槓，這要截圖'],
      ting: ['欸我聽了耶'],
      tsumo: ['自摸～要發限動'],
      ron: ['胡了！'],
      dealIn: ['蛤？這張有人要喔'],
      otherWin: ['好喔'],
      matchWin: ['這要打卡'],
      matchLose: ['我本來就只是湊人數的'],
      reply: ['喔，好喔', '你好吵喔', '好喔，已讀不回', '你這樣很像我們教授'],
      friend: ['欸你來了，我剛好不想寫報告', '今天換我罩你'],
      rival: ['又是你喔，好喔', '你是不是每次都放給我？'],
      revenged: ['蛤，被你討回去了'],
      slow: ['我可以先滑一下 IG 嗎？', '好久喔，我影片都看完了'],
      laugh: ['欸這個可以發限動', '笑死，好慘'],
    },
  },
  queshen: {
    id: 'queshen',
    tempo: 1.15,
    name: '雀神',
    bio: '傳說中的雀神。話很少，幾乎不放槍。',
    look: { skin: SKIN2, hair: 'slick', hairColor: '#e8e8e8', shirt: '#1d2a4a', bg: '#dfe4ee', extras: ['sunglasses'] },
    style: { speed: 0.5, defense: 1, greed: 0.45, mistakes: 0 },
    skill: { id: 'lucky', uses: 2 },
    lines: {
      hello: ['……開始吧。'],
      pon: ['碰。'],
      chi: ['吃。'],
      kong: ['槓。'],
      ting: ['你聽得到嗎？牌的聲音。'],
      tsumo: ['自摸。'],
      ron: ['胡。'],
      dealIn: ['有意思。'],
      otherWin: ['不錯。'],
      matchWin: ['還差得遠。'],
      matchLose: ['……你，就是下一個雀神。'],
      reply: ['……哼。', '話多的人，牌會亂。', '……無聊。', '你的嘴，比你的牌快。'],
      friend: ['……你來了。', '……坐。今天，好好打。'],
      skill: ['……牌，過來。'],
      rival: ['又是你。', '你的牌，我看得很清楚。'],
      revenged: ['……扯平了。'],
      slow: ['……猶豫，就會敗。', '牌，不等人。'],
      laugh: ['……果然。', '破綻。'],
    },
  },
  longge: {
    id: 'longge',
    tempo: 1.0,
    name: '龍哥',
    bio: '老牌麻將館老闆。什麼大風大浪都見過。',
    look: { skin: SKIN2, hair: 'slick', hairColor: '#1a1a1a', shirt: '#b3261e', bg: '#ffe4e0', extras: ['mustache'] },
    style: { speed: 0.7, defense: 0.75, greed: 0.7, mistakes: 0.05 },
    skill: { id: 'swap', uses: 2 },
    lines: {
      hello: ['在我的館子，規矩最重要'],
      pon: ['碰'],
      chi: ['吃'],
      kong: ['槓'],
      ting: ['小心了'],
      tsumo: ['自摸，收錢'],
      ron: ['胡。你太急了'],
      dealIn: ['哼'],
      otherWin: ['好牌'],
      matchWin: ['常來坐'],
      matchLose: ['江山代有人才出'],
      reply: ['在我的館子，說話小心點', '哼，嘴上功夫', '在我的館子，嗆人要付錢', '年輕人，舌頭留著吃飯用'],
      friend: ['你來了，老位子幫你留著', '在我的館子，你是自己人'],
      skill: ['換一張，手氣就回來了'],
      rival: ['你欠我的，還沒還完', '又是你，在我館子裡要小心'],
      revenged: ['哼，這筆帳清了'],
      slow: ['我的館子是算時間收費的', '再不打，我要收你包廂費了'],
      laugh: ['哼，不自量力', '這張，是繳給館子的吧'],
    },
  },
  coco: {
    id: 'coco',
    tempo: 0.9,
    name: 'Coco',
    bio: '麻將直播主。很會演，也真的很會打。',
    look: { skin: SKIN, hair: 'ponytail', hairColor: '#ff6f91', shirt: '#1d2a4a', bg: '#ffe6f0', extras: ['earrings', 'headphones'] },
    style: { speed: 0.6, defense: 0.7, greed: 0.5, mistakes: 0.05 },
    skill: { id: 'peek', uses: 1 },
    lines: {
      hello: ['哈囉聊天室！今天挑戰雀神～'],
      pon: ['碰！聊天室刷一波'],
      chi: ['吃～這個判斷給幾分？'],
      kong: ['槓！斗內破千我就再槓'],
      ting: ['聽牌了，大家猜我聽什麼'],
      tsumo: ['自摸！！感謝斗內'],
      ron: ['胡了～這張我等好久'],
      dealIn: ['剪掉剪掉，這段不要播'],
      otherWin: ['好啦，給你一個讚'],
      matchWin: ['記得訂閱開小鈴鐺～'],
      matchLose: ['今天的精華就是你了'],
      reply: ['聊天室說你好好笑', '欸，這段我要剪起來', '聊天室都在刷你好嗆欸！', '好喔，這段我要做成梗圖'],
      friend: ['聊天室！我的好朋友來了～', '今天跟你一起開台好不好'],
      skill: ['偷看一下下～聊天室不要說喔'],
      rival: ['聊天室在問，你是不是我請來的？', '又是你！觀眾最愛看你送分了'],
      revenged: ['欸欸欸，這段不要播！'],
      slow: ['聊天室都在刷「快打」喔！', '觀眾要睡著了啦～'],
      laugh: ['聊天室在刷好慘好慘！', '這段精華我剪起來了'],
    },
  },
  // ---------- 第 5 關：颱風夜民宿 ----------
  captain: {
    id: 'captain',
    tempo: 0.9,
    name: '船長阿海',
    bio: '跑了四十年船的老船長。颱風天回港，最愛做碰碰胡。',
    look: { skin: '#d9a07a', hair: 'short', hairColor: '#6b6b6b', shirt: '#1f4e79', bg: '#e3f0fb', extras: ['cap', 'beard'], capColor: '#1d2a4a' },
    style: { speed: 0.7, defense: 0.3, greed: 0.75, mistakes: 0.25 },
    lines: {
      hello: ['風再大，牌照打！', '今天不出海，陪你們摸兩圈'],
      pon: ['碰！收網！', '碰啦！'],
      chi: ['吃一口'],
      kong: ['槓！大魚上鉤！'],
      ting: ['浪要來了喔'],
      tsumo: ['自摸！滿載而歸！'],
      ron: ['胡啦！謝謝你的魚'],
      dealIn: ['哎呀，漏網了'],
      otherWin: ['好啦，這網給你'],
      exhausted: ['流局，跟颱風一樣過去就好'],
      matchWin: ['今晚大豐收！'],
      matchLose: ['明天天氣好了再來！'],
      reply: ['少年仔，海上講話要小心', '哈哈哈，有膽量', '少年仔，海上的浪比你嗆多了', '哈哈，你這條小魚還蠻會跳'],
      friend: ['你來了！船長請你喝熱茶', '颱風天有你在就不無聊'],
      rival: ['又是你這條魚！', '少年仔，你每次都自己游進我的網'],
      revenged: ['哈哈，這次換我被釣了'],
      slow: ['你這樣打，船都要擱淺了', '颱風都走了，你還沒打'],
      laugh: ['哈哈，又一條魚上鉤了！', '浪一來，你就翻船了'],
    },
  },
  xiuqin: {
    id: 'xiuqin',
    tempo: 1.05,
    name: '秀琴姐',
    bio: '海邊民宿老闆娘。一邊打牌一邊煮宵夜，防守很穩。',
    look: { skin: SKIN, hair: 'bun', hairColor: '#4a3426', shirt: '#f29e4c', bg: '#fff1e0', extras: ['earrings'] },
    style: { speed: 0.45, defense: 0.65, greed: 0.3, mistakes: 0.3 },
    lines: {
      hello: ['來來來，先喝碗薑湯再打', '停電了也沒關係，我有蠟燭'],
      pon: ['碰～這張我收下了'],
      chi: ['吃一下喔'],
      kong: ['槓！加菜加菜！'],
      ting: ['嗯～差不多可以開飯了'],
      tsumo: ['自摸！宵夜我請！'],
      ron: ['胡囉～不好意思啦'],
      dealIn: ['哎唷，給你給你'],
      otherWin: ['好手氣耶'],
      exhausted: ['流局，來吃點心'],
      matchWin: ['今晚住宿費打八折！'],
      matchLose: ['下次颱風再來挑戰～'],
      reply: ['喲，客人很有精神喔', '再嗆就沒有宵夜吃喔', '再嗆，明天早餐沒有你的份', '好好好，你最厲害～'],
      friend: ['老客人來了！房間幫你留好了', '你來我就去煮麵'],
      rival: ['又是你呀，宵夜錢你付喔', '你是不是很喜歡請姐姐吃宵夜？'],
      revenged: ['好啦好啦，宵夜姐姐請'],
      slow: ['宵夜都要煮好了，你還沒打', '慢慢來，姐先去攪一下湯'],
      laugh: ['哎呀，這樣不行喔～', '呵呵，放槍要罰洗碗喔'],
    },
  },
  leo: {
    id: 'leo',
    tempo: 1.2,
    name: 'Leo',
    bio: '從柏林來的背包客，被颱風困在民宿，剛學會打麻將。',
    look: { skin: '#f3d3bd', hair: 'spiky', hairColor: '#c9a36b', shirt: '#3aa76d', bg: '#e6f7ee' },
    style: { speed: 0.6, defense: 0.25, greed: 0.4, mistakes: 0.55 },
    skill: { id: 'lucky', uses: 1 },
    lines: {
      hello: ['哈囉！我在學台灣麻將！', '颱風好可怕，打麻將比較不可怕'],
      pon: ['碰！我會說碰了！'],
      chi: ['吃！這個我知道'],
      kong: ['槓！是這樣用嗎？'],
      ting: ['我好像……聽了？'],
      tsumo: ['自摸！太好了！'],
      ron: ['胡了！真的嗎？'],
      dealIn: ['喔不！'],
      otherWin: ['好厲害！教我！'],
      exhausted: ['流局是什麼？沒人贏？'],
      matchWin: ['我要寫在旅遊日記！'],
      matchLose: ['台灣麻將好難，但是好好玩'],
      skill: ['新手的好運氣，來吧！'],
      reply: ['我聽不懂，可是我覺得你在嗆我', '謝謝？', '我學會一個新的中文：很嗆！', '你在說什麼？我只聽懂「碰」'],
      friend: ['朋友！你又來了！', '我練習了很多，這次會贏你！'],
      rival: ['又是你！我的好朋友！', '你是我的幸運符嗎？'],
      revenged: ['喔不，你回來了！'],
      slow: ['在德國，我們打牌比較快', '需要我等你嗎？我有很多時間'],
      laugh: ['哈哈！這個我懂，這叫放槍！', '喔不，好慘，可是好好笑'],
    },
  },
  // ---------- 第 6 關：全國麻將大賽 ----------
  acai: {
    id: 'acai',
    tempo: 1.2,
    name: '阿財伯',
    bio: '屏東柑仔店門口打了五十年的「南部冠軍」。孫子偷偷幫他報名全國大賽。',
    look: { skin: SKIN2, hair: 'bald', hairColor: '#3a2618', shirt: '#2e8b57', bg: '#eaf6ec', extras: ['glasses', 'mustache'] },
    style: { speed: 0.45, defense: 0.75, greed: 0.45, mistakes: 0.1 },
    lines: {
      hello: ['南部來的，請多指教', '打了一輩子，第一次上電視'],
      pon: ['碰，足讚！'],
      chi: ['吃，拍謝喔'],
      kong: ['槓，穩穩啊來'],
      ting: ['差不多囉'],
      tsumo: ['自摸，歹勢歹勢'],
      ron: ['胡，承讓'],
      dealIn: ['唉，老花眼'],
      otherWin: ['少年仔有夠厲害'],
      exhausted: ['流局，喝茶'],
      matchWin: ['冠軍獎盃要帶回去給孫子看'],
      matchLose: ['輸給年輕人，心甘情願'],
      reply: ['少年仔，氣定神閒才會贏', '呵呵，好膽', '少年仔，嘴巴甜一點才會贏', '阿伯打牌的時候，你還在喝奶'],
      friend: ['老朋友，今天也好好打', '看到你就想起我年輕的時候'],
      rival: ['少年仔，又是你喔', '你每次都來阿伯這裡繳學費'],
      revenged: ['呵呵，被你討回去了'],
      slow: ['阿伯等到都要睡午覺了', '慢是慢，也不要慢到天黑啊'],
      laugh: ['呵呵，少年仔要多練', '這張阿伯三十年前就不打了'],
    },
  },
  nova: {
    id: 'nova',
    tempo: 0.7,
    name: 'Nova',
    bio: '職業電競選手，手速每分鐘四百下。來學麻將練耐心，結果迷上了。',
    look: { skin: SKIN, hair: 'ponytail', hairColor: '#7c4dff', shirt: '#2b2f3a', bg: '#efe9ff', extras: ['headphones'] },
    style: { speed: 0.85, defense: 0.35, greed: 0.5, mistakes: 0.15 },
    skill: { id: 'swap', uses: 1 },
    lines: {
      hello: ['準備好了嗎？手速拉滿！', '今天目標：全場最快胡牌'],
      pon: ['碰！手速！'],
      chi: ['吃！連段！'],
      kong: ['槓！爆發！'],
      ting: ['大招準備好了'],
      tsumo: ['自摸！完美操作！'],
      ron: ['胡！你走位失誤了'],
      dealIn: ['這把我的鍋'],
      otherWin: ['好啦，下把再來'],
      exhausted: ['平手，加賽！'],
      matchWin: ['冠軍到手，感謝觀眾！'],
      matchLose: ['回去看重播檢討'],
      skill: ['換一張，操作一下'],
      reply: ['嘴砲沒有用，實力說話', '截圖了喔', '嘴砲技能點滿了喔？', '你是在打麻將還是打嘴砲？'],
      friend: ['老隊友！這場我們一起衝', '你的打法我研究過了'],
      rival: ['又是你，送頭仔', '你是我的固定經驗值'],
      revenged: ['被反打了，這波我的'],
      slow: ['你的反應時間比我阿嬤還慢', '掛機了嗎？要不要檢舉？'],
      laugh: ['這波你送了', '哈，操作失誤'],
    },
  },
  zheng: {
    id: 'zheng',
    tempo: 1.25,
    name: '鄭警官',
    bio: '退休刑警，最會看人。聽牌的人手會停一下，他一眼就看穿。',
    look: { skin: SKIN, hair: 'short', hairColor: '#9aa0a6', shirt: '#374151', bg: '#e5e7eb', extras: ['glasses', 'mustache'] },
    style: { speed: 0.3, defense: 0.9, greed: 0.35, mistakes: 0.05 },
    skill: { id: 'peek', uses: 1 },
    lines: {
      hello: ['三十年刑警，誰在聽牌我一看就知道', '各位，請多指教'],
      pon: ['碰。案情有進展'],
      chi: ['吃。'],
      kong: ['槓。收網'],
      ting: ['嫌疑人快落網了'],
      tsumo: ['證據確鑿，自摸'],
      ron: ['抓到了，就是你'],
      dealIn: ['……這次看走眼'],
      otherWin: ['漂亮，我沒看出來'],
      exhausted: ['流局，懸案'],
      matchWin: ['結案'],
      matchLose: ['這案子，我會再查'],
      skill: ['讓我看看你的底牌'],
      reply: ['你講話的時候眼睛在飄', '我記下來了', '你這句話，我會記在筆錄上', '嗆警察，後果自己負責'],
      friend: ['又見面了，老搭檔', '你今天的眼神，很有自信'],
      rival: ['又是你，我記得你的臉', '你有前科喔，上次放了好幾槍'],
      revenged: ['好，這次換我被抓'],
      slow: ['你手停在那裡很久了，心虛喔？', '想那麼久，是在想怎麼湮滅證據嗎？'],
      laugh: ['人贓俱獲', '我早就說你有嫌疑'],
    },
  },

  // ---------- 全國錦標賽 第 1 站：長春路週賽 ----------
  shange: {
    id: 'shange',
    tempo: 1.1,
    name: '山歌協會',
    bio: '客家山歌協會的老成員。打牌一定要哼歌，心情好手氣就好。',
    look: { skin: SKIN2, hair: 'short', hairColor: '#9aa0a6', shirt: '#2b5d9e', bg: '#e3eef9', extras: ['glasses'] },
    style: { speed: 0.5, defense: 0.3, greed: 0.3, mistakes: 0.55 },
    lines: {
      hello: ['來來來，先唱一段山歌暖暖身', '今天禮拜六，打牌唱歌兩樣都不能少'],
      pon: ['碰～山歌就是要有來有往'],
      chi: ['吃一下，哼哼～'],
      kong: ['槓～聲音要拉長～'],
      ting: ['欸，這首快唱到副歌了'],
      tsumo: ['自摸！這要唱一首慶祝！'],
      ron: ['胡囉！謝謝你捧場'],
      dealIn: ['哎呀，唱到走音了'],
      otherWin: ['好手氣，給你拍拍手'],
      exhausted: ['流局，大家來合唱一首'],
      matchWin: ['今天回去唱給協會的人聽！'],
      matchLose: ['輸了沒關係，歌照唱！'],
      reply: ['年輕人，嗓門大不代表會贏喔', '好好好，唱首歌給你聽', '嗆我？我唱一首回敬你', '你這嗓門，來我們協會唱歌吧'],
      friend: ['你來了！協會的人都在問你', '跟你打牌，心情像唱山歌一樣好'],
      rival: ['又是你呀，來來來，唱一首送給你', '你每次都捧我的場，真感心'],
      revenged: ['哎呀，這下換我走音了'],
      slow: ['我都唱完兩首了，你還沒打', '慢慢想，我再唱一段給你聽'],
      laugh: ['哎喲喂，這要編成山歌了', '哈哈，這一段唱起來一定好聽'],
    },
  },
  daqing: {
    id: 'daqing',
    tempo: 0.95,
    name: '大慶行老闆',
    bio: '大慶行開了三十年。算盤打得比誰都快，能碰就碰。',
    look: { skin: SKIN, hair: 'slick', hairColor: '#2b2b2b', shirt: '#c0762c', bg: '#fdebd3', extras: ['mustache'] },
    style: { speed: 0.7, defense: 0.25, greed: 0.45, mistakes: 0.5 },
    lines: {
      hello: ['店交給老婆顧，我偷溜出來打兩圈', '做生意講信用，打牌也是'],
      pon: ['碰！這筆生意我接了'],
      chi: ['吃，進貨進貨'],
      kong: ['槓！大批進貨！'],
      ting: ['嗯，這批貨快到了'],
      tsumo: ['自摸！今天生意好！'],
      ron: ['胡了，帳記一下'],
      dealIn: ['唉，這筆虧本了'],
      otherWin: ['好啦，算你便宜一點'],
      exhausted: ['流局，今天沒賺也沒賠'],
      matchWin: ['回去跟老婆說今天賺了'],
      matchLose: ['下禮拜再來把本撈回來'],
      reply: ['少年仔，嘴甜一點才會做生意', '你這樣講，我要漲價喔', '嗆一句，加收十塊', '少年仔，做生意要和氣生財'],
      friend: ['老主顧來了！今天打折', '你來我店裡，茶隨便喝'],
      rival: ['老主顧又來了！', '你的帳，我這裡記了好幾筆喔'],
      revenged: ['好，帳清了，算你狠'],
      slow: ['你這樣想，我店都要打烊了', '時間就是錢，我算盤都打好了'],
      laugh: ['這筆帳，我記下了', '哈哈，虧本生意喔'],
    },
  },
  chenji: {
    id: 'chenji',
    tempo: 1.2,
    name: '陳記老街老闆',
    bio: '老街上賣了四十年糕仔。牌跟做生意一樣，慢慢來、穩穩打。',
    look: { skin: SKIN2, hair: 'short', hairColor: '#c9ccd1', shirt: '#6b4f3a', bg: '#f2ebe3', extras: ['cap'], capColor: '#7a1f1f' },
    style: { speed: 0.35, defense: 0.45, greed: 0.3, mistakes: 0.45 },
    lines: {
      hello: ['老街的店開了四十年，牌也打了四十年', '慢慢來，不急'],
      pon: ['碰。'],
      chi: ['吃。'],
      kong: ['槓，老招牌。'],
      ting: ['差不多了'],
      tsumo: ['自摸，老天賞飯吃'],
      ron: ['胡了，歹勢'],
      dealIn: ['老了，看漏了'],
      otherWin: ['有進步喔'],
      exhausted: ['流局，泡茶'],
      matchWin: ['老街的招牌，還沒倒'],
      matchLose: ['年輕人厲害，老街要交給你們了'],
      reply: ['呵呵，火氣不要那麼大', '好啦，聽你的', '呵呵，年輕人火氣大，吃塊糕消消火', '好啦好啦，你說的都對'],
      friend: ['你又來啦，老位子給你坐', '來，先吃塊老街的糕仔'],
      rival: ['又是你喔，歹勢又要收你錢', '你是我店裡的常客了'],
      revenged: ['好，這下扯平了'],
      slow: ['慢慢來沒關係，糕仔也是慢慢蒸的', '欸，你是不是在發呆？'],
      laugh: ['哎，歹勢，我不是在笑你', '這張喔……嘖嘖'],
    },
  },
  // ---------- 全國錦標賽 第 2 站：竹東鎮比賽 ----------
  xiaoliu: {
    id: 'xiaoliu',
    tempo: 0.8,
    name: '小劉',
    bio: '竹東市場幫家裡賣菜，找錢從來不用算。竹東第一快手。',
    look: { skin: SKIN, hair: 'spiky', hairColor: '#1d1d1d', shirt: '#3a6df0', bg: '#e6edff', extras: ['cap'], capColor: '#ef3d5c' },
    style: { speed: 0.8, defense: 0.6, greed: 0.35, mistakes: 0.1 },
    lines: {
      hello: ['竹東第一快手，就是我小劉', '快點快點，打完還要去吃粄條'],
      pon: ['碰！手腳要快！'],
      chi: ['吃！再來再來！'],
      kong: ['槓！'],
      ting: ['嘿，我聽了喔'],
      tsumo: ['自摸！速度就是一切！'],
      ron: ['胡！你太慢了啦'],
      dealIn: ['可惡，太急了'],
      otherWin: ['好啦好啦，下一把'],
      exhausted: ['流局！快洗牌！'],
      matchWin: ['冠軍是我的！'],
      matchLose: ['回去練手速'],
      reply: ['講那麼多，快打啦！', '你是不是怕了？', '講那麼多，手快一點啦！', '嗆完了沒？換我了'],
      friend: ['兄弟！今天一起衝', '你來了，比賽才好玩'],
      rival: ['又是你！上次那幾張謝了', '你每次都慢一步啦'],
      revenged: ['可惡，被你討回去！'],
      slow: ['快點啦，菜都要被搶光了', '你打牌比找零錢還慢欸'],
      laugh: ['哈，太慢了就是這樣', '送上門了，謝啦'],
    },
  },
  xiaohao: {
    id: 'xiaohao',
    tempo: 1.0,
    name: '小豪',
    bio: '打牌只做大牌，小牌胡了也不開心。輸比較多，但贏的時候最爽。',
    look: { skin: SKIN2, hair: 'slick', hairColor: '#3a2618', shirt: '#8b5cf6', bg: '#f1ebff', extras: ['sunglasses'] },
    style: { speed: 0.55, defense: 0.65, greed: 0.7, mistakes: 0.08 },
    lines: {
      hello: ['要打就打大的', '小牌我不胡，要胡就胡大的'],
      pon: ['碰，大牌在路上了'],
      chi: ['吃。'],
      kong: ['槓！加台加台！'],
      ting: ['這把很大喔，小心'],
      tsumo: ['自摸！這才叫豪！'],
      ron: ['胡！台數算一下，嚇死你'],
      dealIn: ['嘖，大牌還沒做完'],
      otherWin: ['小牌而已啦'],
      exhausted: ['流局，可惜我的大牌'],
      matchWin: ['豪氣干雲！'],
      matchLose: ['下次做更大的'],
      reply: ['你那點台數不夠看', '哈，有種來拚大的', '你那點台數，嗆不動我', '有種來拚大的！'],
      friend: ['好兄弟！今天一起做大牌', '跟你打，才夠豪'],
      rival: ['又是你，今天也要送大的嗎？', '你是我的專屬贊助商'],
      revenged: ['嘖，這次換你爽'],
      slow: ['想那麼久，是在做大牌喔？', '要做大牌就快一點啦'],
      laugh: ['放槍還放這麼小，無聊', '哈！至少放大一點嘛'],
    },
  },
  xiaoyuan: {
    id: 'xiaoyuan',
    tempo: 1.15,
    name: '小員',
    bio: '很少說話，默默記住每一張出過的牌。防守很難打穿。',
    look: { skin: SKIN, hair: 'short', hairColor: '#2b2b2b', shirt: '#13a37f', bg: '#e3f7f1', extras: ['glasses'] },
    style: { speed: 0.4, defense: 0.85, greed: 0.3, mistakes: 0.08 },
    lines: {
      hello: ['……請多指教', '我不太說話，專心打牌'],
      pon: ['碰。'],
      chi: ['吃。'],
      kong: ['槓。'],
      ting: ['嗯。'],
      tsumo: ['自摸。'],
      ron: ['胡了。'],
      dealIn: ['……失誤了'],
      otherWin: ['嗯，打得好'],
      exhausted: ['流局。'],
      matchWin: ['……謝謝大家'],
      matchLose: ['我會再努力'],
      reply: ['……你很吵。', '嗯。', '……吵。', '……記下了。'],
      friend: ['……你來了。', '跟你打，我比較會講話'],
      rival: ['……又是你。', '……你的牌，我都記得。'],
      revenged: ['……扯平。'],
      slow: ['……你在想什麼？', '……快。'],
      laugh: ['……預料之中。', '……呵。'],
    },
  },
  // ---------- 全國錦標賽 第 3 站：全國錦標賽 ----------
  dushen: {
    id: 'dushen',
    tempo: 1.25,
    name: '賭神',
    bio: '牌桌上幾乎不失手的傳奇。打牌前一定要吃一塊巧克力。',
    look: { skin: SKIN, hair: 'slick', hairColor: '#1a1a1a', shirt: '#1d2a4a', bg: '#e8ecf5', extras: ['tie'] },
    style: { speed: 0.4, defense: 0.95, greed: 0.55, mistakes: 0.02 },
    skill: { id: 'lucky', uses: 1 },
    lines: {
      hello: ['今天，我只吃巧克力。', '坐吧，開始吧。'],
      pon: ['碰。'],
      chi: ['吃。'],
      kong: ['槓。'],
      ting: ['這一手，我已經看到結局了'],
      tsumo: ['自摸。這張，我早就知道。'],
      ron: ['胡了。承讓。'],
      dealIn: ['……有意思。'],
      otherWin: ['不錯，你有天分。'],
      exhausted: ['流局。下一局。'],
      matchWin: ['牌桌上，我從不失手。'],
      matchLose: ['年輕人，你讓我想起從前的自己。'],
      skill: ['牌，來。'],
      reply: ['沉住氣。', '心急，是牌桌上的大忌。', '年輕人，要不要來塊巧克力？冷靜一下', '嗆我的人，最後都輸了'],
      friend: ['又是你。坐吧。', '我等你很久了。'],
      rival: ['又見面了。', '上次的教訓，你記住了嗎？'],
      revenged: ['……好，你討回去了。'],
      slow: ['猶豫，是賭桌上最貴的東西', '想太久，運氣就跑了'],
      laugh: ['看吧，心急了', '這張，不該打。'],
    },
  },
  duxia: {
    id: 'duxia',
    tempo: 1.0,
    name: '賭俠',
    bio: '講義氣、會看人。只跟高手過招，從不欺負新手。',
    look: { skin: SKIN2, hair: 'short', hairColor: '#2b2b2b', shirt: '#f4f1ea', bg: '#fff4e0', extras: ['sunglasses'] },
    style: { speed: 0.6, defense: 0.88, greed: 0.45, mistakes: 0.04 },
    skill: { id: 'peek', uses: 1 },
    lines: {
      hello: ['行走江湖，講的是一個義字', '朋友，今天各憑本事'],
      pon: ['碰！'],
      chi: ['吃！'],
      kong: ['槓！'],
      ting: ['差一張，就收工了'],
      tsumo: ['自摸！願賭服輸！'],
      ron: ['胡！朋友，承讓了'],
      dealIn: ['好，這張算我的'],
      otherWin: ['好身手！'],
      exhausted: ['流局，再來'],
      matchWin: ['贏得光明正大'],
      matchLose: ['輸了就是輸了，我服'],
      skill: ['讓我看看你的底牌'],
      reply: ['朋友，嘴上功夫沒用', '有膽識，我欣賞', '朋友，嘴上功夫贏不了牌', '好，有膽識，我欣賞'],
      friend: ['朋友！又見面了', '有你在，這桌才有意思'],
      rival: ['朋友，又是你', '你欠我的，今天要不要還？'],
      revenged: ['好！有骨氣，這筆算你的'],
      slow: ['朋友，慢慢想，我等你', '江湖規矩，出牌要快'],
      laugh: ['朋友，這張太冒險了', '這一掌，挨得不輕啊'],
    },
  },
  dusheng: {
    id: 'dusheng',
    tempo: 0.85,
    name: '賭聖',
    bio: '號稱有特異功能，能看穿別人的牌。一緊張就不靈。',
    look: { skin: SKIN, hair: 'spiky', hairColor: '#3a2618', shirt: '#ffb020', bg: '#fff5d6', extras: ['glasses'] },
    style: { speed: 0.7, defense: 0.72, greed: 0.7, mistakes: 0.06 },
    skill: { id: 'swap', uses: 1 },
    lines: {
      hello: ['我的特異功能，今天狀態很好！', '大家好，我是來拿冠軍的'],
      pon: ['碰！哈哈！'],
      chi: ['吃！'],
      kong: ['槓！超能力發動！'],
      ting: ['我感應到了！'],
      tsumo: ['自摸！透視眼發功！'],
      ron: ['胡啦！你的牌我早就看穿了'],
      dealIn: ['哎呀，功力不夠'],
      otherWin: ['你是不是也有特異功能？'],
      exhausted: ['流局，功力要充電'],
      matchWin: ['我就說我有特異功能嘛！'],
      matchLose: ['今天功力耗盡了……'],
      skill: ['變！'],
      reply: ['你這樣講，我要生氣了喔！', '哼，看我的特異功能！', '你這樣講，我要用特異功能了喔！', '哼！我不理你了！'],
      friend: ['好兄弟！你也有特異功能嗎？', '你來了，我功力大增！'],
      rival: ['又是你！我早就感應到你會來', '嘿嘿，特異功能對你特別靈'],
      revenged: ['哎呀，特異功能失靈了！'],
      slow: ['我用透視眼都看完你的牌了，你還沒打', '快一點啦，我的特異功能要沒電了'],
      laugh: ['哈哈哈！我早就感應到了！', '笑死，特異功能說你會放槍'],
    },
  },
}

/** 你可以嗆對手的話（配音用 me-f／me-m 的 taunt.<id>） */
export const TAUNTS: readonly { id: string; text: string }[] = [
  { id: 'hurry', text: '快一點啦！' },
  { id: 'thanks', text: '謝謝喔～' },
  { id: 'nice', text: '好牌！' },
  { id: 'ting', text: '你是不是聽了？' },
  { id: 'dare', text: '這張你也敢打？' },
  { id: 'donate', text: '你是來送錢的嗎？' },
  { id: 'waited', text: '我等很久了喔～' },
  { id: 'teach', text: '要不要我教你？' },
  { id: 'big', text: '這把我要胡大的！' },
  { id: 'luck', text: '手氣這麼好，有拜拜喔？' },
  { id: 'hatch', text: '你在孵蛋喔？' },
  { id: 'face', text: '看你的表情就知道了' },
  { id: 'again', text: '不好意思，又是我～' },
  { id: 'supper', text: '輸的請宵夜喔！' },
]

/**
 * 角色之間鬥嘴：a 先講，b 回一句。同一桌的兩個電腦都在的時候，偶爾會冒出來。
 * 配音的 id 是 <角色>.banter.<第幾組>
 */
export const BANTER: readonly { a: string; b: string; say: string; reply: string }[] = [
  // 巷口麻將：大舅媽、鄒家雀神、小姨丈
  { a: 'meiling', b: 'kai', say: '小姨丈，你那個機率算好了沒啦？', reply: '大舅媽，還差兩個變數……' },
  { a: 'kai', b: 'lin', say: '雀神，這張您覺得危險嗎？', reply: '自己的牌，自己看。' },
  { a: 'lin', b: 'meiling', say: '大舅媽，碰太多，門清就沒了。', reply: '哎唷，碰了才開心嘛！' },
  { a: 'meiling', b: 'lin', say: '雀神今天怎麼都不胡啊？', reply: '急什麼，好牌在後頭。' },
  // 公司尾牙：王經理、小美、阿傑
  { a: 'jie', b: 'wang', say: '經理，這把讓我一下啦！', reply: '年終考績我可沒讓你喔。' },
  { a: 'wang', b: 'xiaomei', say: '小美，放輕鬆，今天不談公事。', reply: '好的經理……那我可以胡您嗎？' },
  { a: 'xiaomei', b: 'jie', say: '阿傑哥，你打好快喔！', reply: '業績就是這樣衝出來的！' },
  { a: 'jie', b: 'xiaomei', say: '小美，新手運也要有個限度吧！', reply: '我也不知道為什麼會這樣～' },
  // 過年回老家：阿嬤、二舅、表妹
  { a: 'erjiu', b: 'ama', say: '媽，今年紅包我一定要贏回來！', reply: '你每年都這樣講。' },
  { a: 'ama', b: 'biaomei', say: '乖孫，手機放下，專心打。', reply: '好啦阿嬤，最後一則。' },
  { a: 'biaomei', b: 'erjiu', say: '二舅，你是不是又聽了？', reply: '小孩子不要亂猜！' },
  { a: 'erjiu', b: 'biaomei', say: '表妹，上大學有沒有學麻將？', reply: '有啊，機率課。' },
  // 雀神挑戰：雀神、龍哥、Coco
  { a: 'coco', b: 'queshen', say: '雀神大大，可以跟聊天室打聲招呼嗎？', reply: '……專心。' },
  { a: 'longge', b: 'coco', say: '小姐，在我館子裡直播要先打招呼。', reply: '龍哥好！聊天室說你很帥～' },
  { a: 'queshen', b: 'longge', say: '龍哥，你的牌，變了。', reply: '哼，看得出來算你厲害。' },
  { a: 'coco', b: 'longge', say: '龍哥，你剛剛是不是換牌？', reply: '在我的館子，沒有這種事。' },
  // 颱風夜民宿：船長阿海、秀琴姐、Leo
  { a: 'captain', b: 'leo', say: '少年仔，你們那邊沒有颱風喔？', reply: '我們有暴風雪，可是沒有麻將！' },
  { a: 'xiuqin', b: 'captain', say: '阿海，少喝一點，你又要亂碰了。', reply: '沒醉沒醉，碰得很準啦！' },
  { a: 'leo', b: 'xiuqin', say: '秀琴姐，宵夜好了嗎？', reply: '胡一把就給你吃～' },
  { a: 'captain', b: 'xiuqin', say: '秀琴，停電了要不要點蠟燭？', reply: '早就準備好了，打到天亮都沒問題。' },
  // 全國麻將大賽：阿財伯、Nova、鄭警官
  { a: 'nova', b: 'acai', say: '阿伯，你手速好慢喔！', reply: '少年仔，慢慢來比較快。' },
  { a: 'zheng', b: 'nova', say: '小姐，你剛剛眼睛飄了一下。', reply: '警官，這裡不是偵訊室啦！' },
  { a: 'acai', b: 'zheng', say: '警官，你看牌還是看人？', reply: '都看。牌不會說謊，人會。' },
  { a: 'nova', b: 'zheng', say: '警官，你是不是在讀我的牌？', reply: '我讀的是你的表情。' },
  // 長春路週賽：山歌協會、大慶行老闆、陳記老街老闆
  { a: 'shange', b: 'daqing', say: '老闆，店不用顧喔？', reply: '老婆在顧啦，你唱你的歌。' },
  { a: 'daqing', b: 'chenji', say: '陳記的，今天糕仔有沒有特價？', reply: '你胡一把，我送你一盒。' },
  { a: 'chenji', b: 'shange', say: '別唱了，專心打。', reply: '唱歌才會手氣好啦！' },
  { a: 'daqing', b: 'shange', say: '這把讓我一下啦！', reply: '讓你可以，先聽我唱完一首。' },
  // 竹東鎮比賽：小劉、小豪、小員
  { a: 'xiaoliu', b: 'xiaohao', say: '小豪，你大牌做好了沒？快一點啦！', reply: '急什麼，豪的東西要慢慢來。' },
  { a: 'xiaohao', b: 'xiaoyuan', say: '小員，你怎麼都不講話？', reply: '……在算你的牌。' },
  { a: 'xiaoyuan', b: 'xiaoliu', say: '小劉，你剛剛打太快了。', reply: '快才會贏啦！' },
  { a: 'xiaoliu', b: 'xiaoyuan', say: '小員，你是不是聽了？', reply: '……你猜。' },
  // 全國錦標賽：賭神、賭俠、賭聖
  { a: 'dusheng', b: 'dushen', say: '前輩，你那塊巧克力可以分我一口嗎？', reply: '贏了這局，整盒給你。' },
  { a: 'duxia', b: 'dusheng', say: '聖哥，別用特異功能，公平點。', reply: '我哪有！我是用眼睛看的！' },
  { a: 'dushen', b: 'duxia', say: '你的眼神，洩漏了你的牌。', reply: '彼此彼此。' },
  { a: 'dusheng', b: 'duxia', say: '俠哥，我感應到你快胡了！', reply: '感應得到，擋得住嗎？' },
  // 第二批（接在後面，前面的配音 id 才不會變）
  { a: 'kai', b: 'meiling', say: '大舅媽，你剛剛那個碰，期望值是負的喔。', reply: '期望值？舅媽只期望今天贏錢啦！' },
  { a: 'meiling', b: 'lin', say: '雀神，你退休金都拿來打牌喔？', reply: '打小的，養老剛好。' },
  { a: 'wang', b: 'jie', say: '阿傑，你上班有打牌這麼認真就好了。', reply: '經理，我上班也很認真打……打電話！' },
  { a: 'xiaomei', b: 'wang', say: '經理，胡您的牌，會影響考績嗎？', reply: '……我們下班不談考績。' },
  { a: 'ama', b: 'erjiu', say: '兒子啊，少喝一點，你又在亂打了。', reply: '媽，我這是戰術！' },
  { a: 'biaomei', b: 'ama', say: '阿嬤，你怎麼都知道我要打什麼？', reply: '阿嬤打牌的時候，你媽都還沒出生。' },
  { a: 'coco', b: 'queshen', say: '雀神大大，聊天室問你有沒有女朋友。', reply: '……打牌。' },
  { a: 'longge', b: 'queshen', say: '雀神，今天館子的茶還合口嗎？', reply: '茶好。牌，還差一點。' },
  { a: 'leo', b: 'captain', say: '船長，颱風天你們都打麻將嗎？', reply: '不然咧？出海喔？' },
  { a: 'xiuqin', b: 'leo', say: 'Leo，今天輸的錢，明天幫我洗床單抵。', reply: '洗床單？這是台灣的規矩嗎？' },
  { a: 'acai', b: 'nova', say: '小姐，你一分鐘按四百下，手不會痠喔？', reply: '阿伯，你一張牌想四百秒，頭不會痛喔？' },
  { a: 'zheng', b: 'acai', say: '阿伯，你孫子幫你報名，你知道嗎？', reply: '知道啊，獎金他說要分一半。' },
  { a: 'chenji', b: 'daqing', say: '大慶的，你帶算盤來做什麼？', reply: '算你今天輸多少啊！' },
  { a: 'shange', b: 'chenji', say: '陳記的，我幫你的糕仔寫一首廣告歌。', reply: '好啊，唱得好聽送你一盒。' },
  { a: 'xiaohao', b: 'xiaoliu', say: '小劉，你快是快，可是胡的都好小。', reply: '小的也是錢啊！' },
  { a: 'xiaoliu', b: 'xiaoyuan', say: '小員，你講一句話會怎樣？', reply: '……會輸。' },
  { a: 'duxia', b: 'dushen', say: '前輩，你的巧克力是不是有加料？', reply: '加了一點……自信。' },
  { a: 'dusheng', b: 'duxia', say: '俠哥，你有沒有被我的特異功能嚇到？', reply: '有，嚇到我想笑。' },
]

/** 快速表情：不唸出來，只跳泡泡（連線時朋友也看得到） */
export const EMOTES: readonly { id: string; emoji: string; text: string }[] = [
  { id: 'wow', emoji: '😱', text: '好險！' },
  { id: 'please', emoji: '🙏', text: '拜託拜託' },
  { id: 'lol', emoji: '😂', text: '笑死' },
  { id: 'argh', emoji: '😤', text: '可惡！' },
  { id: 'tea', emoji: '🍵', text: '慢慢來' },
  { id: 'gg', emoji: '👏', text: '打得好' },
]

/** 嗆聲或表情的泡泡文字；沒有這個 id 就是 null */
export function tauntText(id: string): { text: string; voiced: boolean } | null {
  const t = TAUNTS.find((x) => x.id === id)
  if (t) return { text: t.text, voiced: true }
  const e = EMOTES.find((x) => x.id === id)
  return e ? { text: `${e.emoji} ${e.text}`, voiced: false } : null
}

export function line(ch: Character, key: LineKey, r: number): string | null {
  const ls = ch.lines[key]
  if (!ls || !ls.length) return null
  return ls[Math.floor(r * ls.length) % ls.length]
}
